### ISSUE TITLE
camera not detected -- what do i need to fix?

### ISSUE THREAD

**Issue by prankousky** [flying-pizza-69/GestureX#2] opened 2024-04-15 13:06 UTC
Hi,

I've found this project on reddit and was excited to try it. I am using a Sony Playstation Eye cam.

from `lsusb`: `Bus 003 Device 006: ID 1415:2000 Nam Tai E&E Products Ltd. or OmniVision Technologies, Inc. Sony Playstation Eye`
from `v4l2-ctl --list-devices` : `USB Camera-B4.09.24.1 (usb-0000:11:00.0-4):/dev/video0`

Installed the program as per README.md. When I start it, I get the following output; however, there is no video visible in the app (and it cannot be toggled, either). The camera does not turn on its red LED, either, which it does, when I use it. The computer is capable of working with this camera; when I run  `mpv av://v4l2:/dev/video0 --profile=low-latency --untimed`, I get video output.

**However**, when I start the program via `python3 gui.py`, and **then** try to play the video, it won't work. The video player will time out. So I assume that the program does actually somehow "occupy" the camera stream. When I quit the program, I can play the camera through mpv and other programs again.

```
 python3 gui.py
2024-04-15 15:00:50.370543: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-04-15 15:00:50.396776: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI AVX512_BF16 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-04-15 15:00:50.911297: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
/home/ben/Projekte/code/GestureX/gui.py:91: DeprecationWarning: Gtk.Widget.override_color is deprecated
  separator.override_color(Gtk.StateFlags.NORMAL, Gdk.RGBA(0, 0, 0, 1))
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1713186051.472060   34747 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
I0000 00:00:1713186051.473928   34781 gl_context.cc:344] GL version: 3.2 (OpenGL ES 3.2 Mesa 24.0.4-arch1.2), renderer: AMD Radeon Graphics (radeonsi, raphael_mendocino, LLVM 17.0.6, DRM 3.57, 6.8.4-arch1-1)
Exception in thread Thread-1 (run_video_loop):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ben/Projekte/code/GestureX/gui.py", line 143, in run_video_loop
    model = load_model('mp_hand_gesture')
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ben/.local/lib/python3.11/site-packages/keras/src/saving/saving_api.py", line 191, in load_model
    raise ValueError(
ValueError: File format not supported: filepath=mp_hand_gesture. Keras 3 only supports V3 `.keras` files and legacy H5 format files (`.h5` extension). Note that the legacy SavedModel format is not supported by `load_model()` in Keras 3. In order to reload a TensorFlow SavedModel as an inference-only layer in Keras 3, use `keras.layers.TFSMLayer(mp_hand_gesture, call_endpoint='serving_default')` (note that your `call_endpoint` might have a different name).
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
```

My GPU is `NVIDIA Corporation AD104 [GeForce RTX 4070 Ti] (rev a1)` (don't know if this is relevant, but thought I'd mention it). I'm running my X Desktop via onboard GPU (nvidia is for virtual machines when assigned), so that card would be free -- if needed.

Below are the contents of the mp_hand_gesture folder; it says something about .keras files / h5 extension, which are not in this folder. But I cloned the repo as instructed.

![grafik](https://github.com/flying-pizza-69/GestureX/assets/11297070/193f652b-be96-4176-a2ad-654bda198680)

GUI looks like this. What do I need to fix? Thanks in advance for your support :)

![grafik](https://github.com/flying-pizza-69/GestureX/assets/11297070/85f4b654-b722-4fcb-a147-de03dc770d8b)

**Comment by flying-pizza-69** [comment] 2024-04-15 16:09
Hi, I think the issue is not with the camera but with the Keras version. According to the error you are getting, it seems like you are using Keras version 3 which apparently does not support the file type in which the model is saved. Can you show me the output of:
```
import keras
print(keras.__version__)
```
For me, it is 2.15.0. It must be 3.x.x for you. I will try to fix it for Keras 3 till then.

**Comment by chicco-carone** [comment] 2024-04-15 18:10
I get the same issue and error. For me the output of the version of keras is 3.2.1

**Comment by EmperorProtects** [comment] 2024-04-16 03:16
Got the same issue with keras 321

**Comment by prankousky** [comment] 2024-04-16 04:44
> show me the output of:
> 
> ```
> import keras
> print(keras.__version__)
> ```

Thank you for your quick reply. This is the output, so yeah, I am on 3.2.1

```
Python 3.11.8 (main, Feb 12 2024, 14:50:05) [GCC 13.2.1 20230801] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import keras
2024-04-16 06:42:57.358633: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.

2024-04-16 06:42:57.708553: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI AVX512_BF16 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-04-16 06:42:58.424715: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
>>> print(keras.__version__)
3.2.1

```

**Comment by daniellandau** [comment] 2024-04-16 06:25
Newest tensorflow depends on newer keras, tensorflow==2.15.1 works.

**Comment by prankousky** [comment] 2024-04-16 12:50
It works after `pip3 install tensorflow==2.15.1 --break-system-packages`.

Two questions:

1. is it possible to run this in the background? So `python3 gui.py` to setup the program, but then have it run without the gui (perhaps either minimize it to systray or have something like `python3 gui.py --background --config=~/.config/gesturex/config00.json`)

2. Would it be possible to add a delay? Please look at this screenshot below. Let's say I want to run some bash script, I'd like to run it **once** when it detects the gesture, then perhaps wait until it detects it again?

In other words: user gives makes gesture > execute command; *while* gesture is **still** there, don't do anything **until** *either* a different gesture *or* no gesture at all is detected.

![grafik](https://github.com/flying-pizza-69/GestureX/assets/11297070/768977bf-30a3-432f-9367-92d52d44d2d3)


So if somebody gives thumbs up, only register this thumbs up once (no matter for how long the keep their thumb up); then, when they either make a different gesture, or no gesture is detected at all, allow the program to execute the next action.

While this is great, look at this :laughing: [video](https://imgur.com/a/YoBAYUQ). This is a bit much, of course, but as you can see, even if I try to only give thumbs up for a very short amount of time, the command will be executed too many times to be functional (in this case, switch between current and previous workspace in awesome; this wouldn't work productively because the switch happens way too fast because there is no delay).

Either way, thank you so much for this interesting and fun project. I could imagine some cool use cases. I have an exercise bike in front of the computer. Usually watching either youtube or media from plex while on the bike. Currently, I control this via voice, but it'd be even cooler to give thumbs up to open plex or a fist to open youtube in a new browser tab, for example :)

**Comment by chicco-carone** [comment] 2024-04-16 12:54
> It works after `pip3 install tensorflow==2.15.1 --break-system-packages`.
> 
> Two questions:
> 
> 1. is it possible to run this in the background? So `python3 gui.py` to setup the program, but then have it run without the gui (perhaps either minimize it to systray or have something like `python3 gui.py --background --config=~/.config/gesturex/config00.json`)
> 
> 2. Would it be possible to add a delay? Please look at this screenshot below. Let's say I want to run some bash script, I'd like to run it **once** when it detects the gesture, then perhaps wait until it detects it again?
> 
> In other words: user gives makes gesture > execute command; *while* gesture is **still** there, don't do anything **until** *either* a different gesture *or* no gesture at all is detected.
> 
> ![grafik](https://github.com/flying-pizza-69/GestureX/assets/11297070/768977bf-30a3-432f-9367-92d52d44d2d3)
> 
> 
> So if somebody gives thumbs up, only register this thumbs up once (no matter for how long the keep their thumb up); then, when they either make a different gesture, or no gesture is detected at all, allow the program to execute the next action.
> 
> While this is great, look at this :laughing: [video](https://imgur.com/a/YoBAYUQ). This is a bit much, of course, but as you can see, even if I try to only give thumbs up for a very short amount of time, the command will be executed too many times to be functional (in this case, switch between current and previous workspace in awesome; this wouldn't work productively because the switch happens way too fast because there is no delay).
> 
> Either way, thank you so much for this interesting and fun project. I could imagine some cool use cases. I have an exercise bike in front of the computer. Usually watching either youtube or media from plex while on the bike. Currently, I control this via voice, but it'd be even cooler to give thumbs up to open plex or a fist to open youtube in a new browser tab, for example :)

Using the --break-system-packages options is not a very good idea I would raccomend you to use a venv and install the dependencies there

**Comment by flying-pizza-69** [comment] 2024-04-16 14:56
@prankousky yeah i need to work on a feature so it runs in background or as a daemon. i have never done that thing before so not sure how to do it but i will do it soon. also youre right, thats a major issue with the application right now. i will start working on that first. 

since you have already created a new feature request for both of the issues mentioned above, im going to close this ticket for now and mention in the readme that tensorflow==2.15.1 is required for the project. you can open a new issue or feature request for fixing the program for keras 3 as well. thanks!

@chicco-carone yeah you are also right, i did not expect this project to grow at all and i thought i will be the only user so i wrote a jank code and used --break-system-packages on my pc to use it. i will update the readme with instructions for venv instead of global config. thanks!

**Closed by flying-pizza-69** 2024-04-16 14:56 UTC

**Comment by chicco-carone** [comment] 2024-04-16 17:34
> @prankousky yeah i need to work on a feature so it runs in background or as a daemon. i have never done that thing before so not sure how to do it but i will do it soon. also youre right, thats a major issue with the application right now. i will start working on that first. 
> 
> since you have already created a new feature request for both of the issues mentioned above, im going to close this ticket for now and mention in the readme that tensorflow==2.15.1 is required for the project. you can open a new issue or feature request for fixing the program for keras 3 as well. thanks!
> 
> @chicco-carone yeah you are also right, i did not expect this project to grow at all and i thought i will be the only user so i wrote a jank code and used --break-system-packages on my pc to use it. i will update the readme with instructions for venv instead of global config. thanks!

No problem. I mentioned it here because the only time I used it killed my arch installation definitely and I had to reinstall so to avoid someone coming here after killing their os for no apparent reason
